version: "3"

services:
  backend:
    build: .
    restart: always
    ports:
      - "8080:8080"
    networks:
      - advappdev_reservation-net
    environment:
      - DB_HOST=mysqldb
    depends_on:
      - mysqldb
    volumes:
      - .m2:/root/.m2
  
  mysqldb:
    image: mysql:8.0
    restart: always
    networks:
      - advappdev_reservation-net
    environment:
      MYSQL_DATABASE: db_reservation
      MYSQL_ROOT_PASSWORD: root
    volumes:
      # create tables
      - ./src/main/resources/schema.sql:/docker-entrypoint-initdb.d/1.sql
      # initial data / seed
      - ./src/main/resources/init.sql:/docker-entrypoint-initdb.d/2.sql

networks:
  advappdev_reservation-net:
    external: true