spring:
  main:
    allow-circular-references: true
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/db_reservation?allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      dialect: org.hibernate.dialect.MySQL8Dialect
