jwt:
  private.key: classpath:app.key
  public.key: classpath:app.pub
spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
      naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/db_reservation?allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
