CREATE TABLE apartment (
  apartmentId INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(45) NOT NULL
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE users (
  userId INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
  username VARCHAR(45) NOT NULL,
  password VARCHAR(64) NOT NULL
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;